//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonGia
    {
        public int maLoaiPhong { get; set; }
        public int maHinhThuc { get; set; }
        public Nullable<double> donGia1 { get; set; }
        public Nullable<double> keTiep { get; set; }
        public Nullable<double> tienQuaGio { get; set; }
    
        public virtual HinhThuc HinhThuc { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
    }
}
