//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhThuc
    {
        public HinhThuc()
        {
            this.DonGias = new HashSet<DonGia>();
            this.PhieuThues = new HashSet<PhieuThue>();
        }
    
        public int maHinhThuc { get; set; }
        public string tenHinhThuc { get; set; }
    
        public virtual ICollection<DonGia> DonGias { get; set; }
        public virtual ICollection<PhieuThue> PhieuThues { get; set; }
    }
}
