//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int maHD { get; set; }
        public Nullable<int> maPhieu { get; set; }
        public Nullable<double> tongTien { get; set; }
        public Nullable<System.DateTime> ngayLap { get; set; }
    
        public virtual PhieuThue PhieuThue { get; set; }
    }
}
