//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public KhachHang()
        {
            this.PhieuThues = new HashSet<PhieuThue>();
        }
    
        public int maKH { get; set; }
        public string tenKhachHang { get; set; }
        public string soXe { get; set; }
        public string soCMND { get; set; }
        public string soDienThoai { get; set; }
    
        public virtual ICollection<PhieuThue> PhieuThues { get; set; }
    }
}
