//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class KSEntities : DbContext
    {
        public KSEntities()
            : base("name=KSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DichVu> DichVus { get; set; }
        public DbSet<DonGia> DonGias { get; set; }
        public DbSet<HinhThuc> HinhThucs { get; set; }
        public DbSet<HoaDon> HoaDons { get; set; }
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<LoaiPhong> LoaiPhongs { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<PhieuThue> PhieuThues { get; set; }
        public DbSet<Phong> Phongs { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<SuDungDichVu> SuDungDichVus { get; set; }
    
        public virtual ObjectResult<sp_DanhSachSuDungDV_Result> sp_DanhSachSuDungDV(Nullable<int> maPhieuThue)
        {
            var maPhieuThueParameter = maPhieuThue.HasValue ?
                new ObjectParameter("maPhieuThue", maPhieuThue) :
                new ObjectParameter("maPhieuThue", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DanhSachSuDungDV_Result>("sp_DanhSachSuDungDV", maPhieuThueParameter);
        }
    
        public virtual int sp_GiamDichVuSuDung(Nullable<int> masuDung)
        {
            var masuDungParameter = masuDung.HasValue ?
                new ObjectParameter("masuDung", masuDung) :
                new ObjectParameter("masuDung", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GiamDichVuSuDung", masuDungParameter);
        }
    
        public virtual ObjectResult<sp_LayDanhSachCaiDat_Result> sp_LayDanhSachCaiDat()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDanhSachCaiDat_Result>("sp_LayDanhSachCaiDat");
        }
    
        public virtual ObjectResult<sp_LayDanhSachDichVu_Result> sp_LayDanhSachDichVu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDanhSachDichVu_Result>("sp_LayDanhSachDichVu");
        }
    
        public virtual ObjectResult<sp_LayDanhSachHinhThuc_Result> sp_LayDanhSachHinhThuc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDanhSachHinhThuc_Result>("sp_LayDanhSachHinhThuc");
        }
    
        public virtual ObjectResult<sp_LayDanhSachPhong_Result> sp_LayDanhSachPhong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDanhSachPhong_Result>("sp_LayDanhSachPhong");
        }
    
        public virtual ObjectResult<sp_LayDonGia_Result> sp_LayDonGia(Nullable<int> maHinhThuc, Nullable<int> maLoaiPhong)
        {
            var maHinhThucParameter = maHinhThuc.HasValue ?
                new ObjectParameter("maHinhThuc", maHinhThuc) :
                new ObjectParameter("maHinhThuc", typeof(int));
    
            var maLoaiPhongParameter = maLoaiPhong.HasValue ?
                new ObjectParameter("maLoaiPhong", maLoaiPhong) :
                new ObjectParameter("maLoaiPhong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDonGia_Result>("sp_LayDonGia", maHinhThucParameter, maLoaiPhongParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_LayLoaiPhongCuaPhong(Nullable<int> maPhong)
        {
            var maPhongParameter = maPhong.HasValue ?
                new ObjectParameter("maPhong", maPhong) :
                new ObjectParameter("maPhong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_LayLoaiPhongCuaPhong", maPhongParameter);
        }
    
        public virtual ObjectResult<Nullable<double>> sp_LayThoiGianThem()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<double>>("sp_LayThoiGianThem");
        }
    
        public virtual ObjectResult<sp_LayThongTinPhieuThue_Result> sp_LayThongTinPhieuThue(Nullable<int> maPhong)
        {
            var maPhongParameter = maPhong.HasValue ?
                new ObjectParameter("maPhong", maPhong) :
                new ObjectParameter("maPhong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayThongTinPhieuThue_Result>("sp_LayThongTinPhieuThue", maPhongParameter);
        }
    
        public virtual int sp_ThemDichVuSuDung(Nullable<int> maDichVu, Nullable<int> maPhieuThue)
        {
            var maDichVuParameter = maDichVu.HasValue ?
                new ObjectParameter("maDichVu", maDichVu) :
                new ObjectParameter("maDichVu", typeof(int));
    
            var maPhieuThueParameter = maPhieuThue.HasValue ?
                new ObjectParameter("maPhieuThue", maPhieuThue) :
                new ObjectParameter("maPhieuThue", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemDichVuSuDung", maDichVuParameter, maPhieuThueParameter);
        }
    
        public virtual ObjectResult<sp_TimKhachHangByCMND_Result> sp_TimKhachHangByCMND(string soCMND)
        {
            var soCMNDParameter = soCMND != null ?
                new ObjectParameter("soCMND", soCMND) :
                new ObjectParameter("soCMND", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKhachHangByCMND_Result>("sp_TimKhachHangByCMND", soCMNDParameter);
        }
    
        public virtual int sp_XoaSuDungDichVu(Nullable<int> masuDung)
        {
            var masuDungParameter = masuDung.HasValue ?
                new ObjectParameter("masuDung", masuDung) :
                new ObjectParameter("masuDung", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaSuDungDichVu", masuDungParameter);
        }
    
        public virtual int sp_DoiTrangThaiPhong(Nullable<int> maPhong, Nullable<byte> trangThai)
        {
            var maPhongParameter = maPhong.HasValue ?
                new ObjectParameter("maPhong", maPhong) :
                new ObjectParameter("maPhong", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("trangThai", trangThai) :
                new ObjectParameter("trangThai", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DoiTrangThaiPhong", maPhongParameter, trangThaiParameter);
        }
    }
}
