//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThue
    {
        public PhieuThue()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.SuDungDichVus = new HashSet<SuDungDichVu>();
        }
    
        public int maPhieu { get; set; }
        public Nullable<int> maPhong { get; set; }
        public Nullable<int> maHinhThuc { get; set; }
        public Nullable<int> maKhachHang { get; set; }
        public Nullable<System.DateTime> gioVao { get; set; }
        public Nullable<System.DateTime> gioTra { get; set; }
        public Nullable<double> donGia { get; set; }
        public Nullable<double> keTiep { get; set; }
        public Nullable<double> tienQuaGio { get; set; }
    
        public virtual HinhThuc HinhThuc { get; set; }
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual Phong Phong { get; set; }
        public virtual ICollection<SuDungDichVu> SuDungDichVus { get; set; }
    }
}
