//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        public Phong()
        {
            this.PhieuThues = new HashSet<PhieuThue>();
        }
    
        public int maPhong { get; set; }
        public string soPhong { get; set; }
        public Nullable<int> maLoaiPhong { get; set; }
        public Nullable<byte> trangThai { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual LoaiPhong LoaiPhong { get; set; }
        public virtual ICollection<PhieuThue> PhieuThues { get; set; }
    }
}
