//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuDungDichVu
    {
        public int maSuDung { get; set; }
        public Nullable<int> maDichVu { get; set; }
        public Nullable<int> maPhieuThue { get; set; }
        public double donGia { get; set; }
        public int soLuong { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual PhieuThue PhieuThue { get; set; }
    }
}
